from pathlib import Path
from wordcloud import WordCloud
import random

OUT = Path(__file__).resolve().parents[1] / 'public'
FONT = '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'
PAPER = '#FFF8E7'
PALETTE = ['#7D2B19', '#A14722', '#8E3D28', '#5B5148', '#7B6330', '#333399', '#6B5B4C', '#4A4A4A']

frequencies = {
    'AI/ML for Science': 110,
    'CADD': 94,
    'molecular simulation': 90,
    'chemical physics': 88,
    'protein design': 84,
    'free-energy methods': 82,
    'molecular docking': 80,
    'statistical mechanics': 77,
    'biomolecular AI': 74,
    'geometric deep learning': 71,
    'virtual screening': 69,
    'computational chemistry': 67,
    'mathematical biology': 65,
    'molecular dynamics': 64,
    'protein foundation models': 63,
    'chromatin modeling': 61,
    'drug discovery': 60,
    'quantum chemistry': 59,
    'uncertainty calibration': 58,
    'scientific workflows': 57,
    'target discovery': 56,
    'generative models': 55,
    'diffusion models': 54,
    'protein safety': 53,
    '3D meshes': 52,
    'point clouds': 51,
    'antibody design': 50,
    'genome modeling': 49,
    'single-cell genomics': 48,
    'renormalization group': 47,
    'stochastic processes': 46,
    'reaction diffusion': 45,
    'electronic structure': 44,
    'density functional theory': 43,
    'Monte Carlo': 42,
    'molecular topology': 41,
    'protein-ligand co-folding': 40,
    'sequence-structure-function': 39,
    'mechanistic validation': 38,
    'robust optimization': 37,
    'scientific inference': 36,
    'high-performance computing': 35,
    'adversarial evaluation': 34,
    'retrosynthesis': 33,
    'reaction mechanisms': 32,
    'biochemical diffusion': 31,
    'phase transitions': 30,
    'dynamical systems': 29,
    'agentic chemistry': 28,
    'scientific decision-making': 27,
    'TBXT': 31,
    'ChromoGen V2': 30,
    'PRISM': 29,
    'EVEdesign': 28,
    'V2M-Engine': 27,
    'ChemAgent-QSM': 27,
    'Antibody RL': 26,
    'Kupcinet-Getz': 24,
    'Özkırşehirli Group': 23,
    'GNINA': 30,
    'AutoDock Vina': 29,
    'RDKit': 29,
    'QSAR': 28,
    'BRICS': 26,
    'Boltz-2': 27,
    'MMGBSA': 25,
    'FEP': 25,
    'OpenMM': 24,
    'OpenFE': 23,
    'PySCF': 24,
    'PyTorch': 25,
    'CUDA': 23,
    'GNNs': 24,
    'Transformers': 24,
    'PPO': 21,
    'PINNs': 21,
    'neural ODEs': 22,
    'Gillespie SSA': 20,
    'Euler-Maruyama': 18,
    'LangGraph': 22,
    'FastAPI': 21,
    'Python': 23,
    'C/C++': 19,
    'Linux': 18,
    'SLURM': 18,
    'HPC': 22,
    'Tanimoto': 18,
    'PAINS filters': 18,
    'ADMET': 20,
    'ESOL': 17,
    'Morgan fingerprints': 17,
    'sequence modeling': 19,
    'structure prediction': 21,
    'immune-state modeling': 19,
    'QTL colocalization': 18,
    'Perturb-seq': 17,
    'chromatin diffusion': 20,
    'Plate-C': 16,
    'Easy Dip-C': 16,
    'CHARM': 16,
    'OAS': 15,
    'SAbDab': 15,
    'IEDB': 15,
    'IGFold': 16,
    'AlphaFold-Multimer': 17,
    'MIT CSAIL': 22,
    'MIT Chemistry': 21,
    'MIT Physics': 20,
    'A*STAR EDDC': 18,
    'Weizmann Institute': 17,
    'Harvard Medical School': 17,
    'Columbia University': 16,
    'MIT BioMakers': 15,
    'philosophy of science': 16,
    'epistemology': 14,
    'algorithms': 18,
    'computable representations': 21,
    'testable models': 18,
    'auditable pipelines': 18,
}

# Deterministic palette based on the word itself, with the largest terms biased toward burgundy.
def color_func(word, font_size, position, orientation, random_state=None, **kwargs):
    if font_size >= 105:
        return '#7D2B19'
    if font_size >= 72:
        return '#A14722'
    seed = sum(ord(c) for c in word) + font_size
    return PALETTE[seed % len(PALETTE)]

wc = WordCloud(
    width=2400,
    height=1260,
    background_color=PAPER,
    mode='RGB',
    font_path=FONT,
    max_words=130,
    min_font_size=24,
    max_font_size=190,
    prefer_horizontal=1.0,
    relative_scaling=0.42,
    margin=14,
    random_state=26,
    collocations=False,
    color_func=color_func,
)
wc.generate_from_frequencies(frequencies)
wc.to_file(str(OUT / 'word-cloud.png'))
(OUT / 'photos' / 'wordcloud.png').write_bytes((OUT / 'word-cloud.png').read_bytes())
